version: '2'

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid; bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mailhog
      - webpack
    environment:
      - MAILHOG=true
      - RAILS_ENV=development
      - SELENIUM_PORT=4444
      - SERVER_PORT=3000
      - WEBPACKER_DEV_SERVER_HOST=webpack
    image: zedtux/rails5-react
    networks:
      - rrdb
    ports:
      - "3000:3000"
    volumes_from:
      - bundle
  bundle:
    command: echo Bundler data container
    image: zedtux/rails5-react
    volumes:
      - /usr/local/bundle
  mailhog:
    image: mailhog/mailhog
    networks:
      - rrdb
    ports:
      - "1025:1025"
      - "8025:8025"
  selenium:
    image: selenium/standalone-chrome:3.11.0-antimony
    networks:
      - rrdb
    # For Debug (And uncomment the `ports` node to connect with VNC)
    # image: selenium/standalone-chrome-debug:3.11.0-antimony
    # ports:
    #   - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
  webpack:
    command: bin/webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    image: zedtux/rails5-react
    networks:
      - rrdb
    ports:
      - "3035:3035"
    volumes_from:
      - bundle

networks:
  rrdb:
