---
default: &default
  adapter: postgresql

# Local development only
development: &local
  <<: *default
  host: localhost
  username: eugene
  password:
  database: timesheets

test: &test
  <<: *default
  <<: *local
  database: timesheets-test

production:
  <<: *default
  host: <%= ENV["DATABASE_URL"] %>

cypress:
  <<: *test
  database: timesheets-cypress
