---
default: &default
  adapter: postgresql

# Local development only
development: &local
  <<: *default
  host: localhost
  username: eugene
  password:
  database: timesheets

test:
  <<: *default
  <<: *local
  database: timesheets-test
