# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c28af8bc720ca990dd67f984484cc2fde01c15719452e6e004140bead55a8e9e7f09cf8283f5409e54a8aaec74f9744881199cf36d39e6675336091c8b5490f7
  jwt_secret: 'super random key'
  jwt_expiration_hours: 24

test:
  secret_key_base: d8ca401980bbb97dcb87fe6050b0c0927d23835ee3fdea250e223611e1aa71d03128f3f38869301966bf0609c2585b36a24bdae3d8d3b91571608630c29a0097
  jwt_secret: 'another super random key'
  jwt_expiration_hours: 24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: 'even more super random key'
  jwt_expiration_hours: 6

cypress:
  secret_key_base: c28af8bc720ca990dd67f984484cc2fde01c15719452e6e004140bead55a8e9e7f09cf8283f5409e54a8aaec74f9744881199cf36d39e6675336091c8b5490f7
  jwt_secret: 'super random key'
  jwt_expiration_hours: 24
