export default {
  DELETE_USER_REQUEST: 'HOME_DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'HOME_DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'HOME_DELETE_USER_FAILURE',

  GET_ALL_USERS_REQUEST: 'HOME_GET_ALL_USERS_REQUEST',
  GET_ALL_USERS_SUCCESS: 'HOME_GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'HOME_GET_ALL_USERS_FAILURE',
}
