export default {
  CHANGE_PASSWORD_REQUEST: 'DEVISE_CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'DEVISE_CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'DEVISE_CHANGE_PASSWORD_FAILURE',

  CONFIRMATION_REQUEST: 'DEVISE_CONFIRMATION_REQUEST',
  CONFIRMATION_SUCCESS: 'DEVISE_CONFIRMATION_SUCCESS',
  CONFIRMATION_FAILURE: 'DEVISE_CONFIRMATION_FAILURE',

  CONFIRMATION_RESEND_REQUEST: 'DEVISE_CONFIRMATION_RESEND_REQUEST',
  CONFIRMATION_RESEND_SUCCESS: 'DEVISE_CONFIRMATION_RESEND_SUCCESS',
  CONFIRMATION_RESEND_FAILURE: 'DEVISE_CONFIRMATION_RESEND_FAILURE',

  LOGIN_REQUEST: 'DEVISE_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'DEVISE_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'DEVISE_LOGIN_FAILURE',

  LOGOUT: 'DEVISE_LOGOUT',

  PASSWORD_RESET_REQUEST: 'DEVISE_PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS: 'DEVISE_PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILURE: 'DEVISE_PASSWORD_RESET_FAILURE',

  REGISTER_REQUEST: 'DEVISE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'DEVISE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'DEVISE_REGISTER_FAILURE',

  UNLOCK_RESEND_REQUEST: 'DEVISE_UNLOCK_RESEND_REQUEST',
  UNLOCK_RESEND_SUCCESS: 'DEVISE_UNLOCK_RESEND_SUCCESS',
  UNLOCK_RESEND_FAILURE: 'DEVISE_UNLOCK_RESEND_FAILURE',

  UNCLOCK_REQUEST: 'DEVISE_UNCLOCK_REQUEST',
  UNCLOCK_SUCCESS: 'DEVISE_UNCLOCK_SUCCESS',
  UNCLOCK_FAILURE: 'DEVISE_UNCLOCK_FAILURE'
}
